apiVersion: v1
kind: Secret
metadata:
    name: podinfo-values
    namespace: podinfo
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:V07eyyFXIW1f4egFT7KCxLOkH2c1pPgJwlujRfBM8biurTgSftU1FtT919rfdX9qSdH1xcsL1r08Fp99Bw==,iv:7Wtx+ZS7ixWukvQ8Z8XSr1i7WGPRGIHrdz8nRol31P8=,tag:VPQHI/a8mA3car6/44t8qw==,type:str]
sops:
    age:
        - recipient: age16f57mdcye3txnjuk3kuhquvfvzwl2gqlqzalwh0082z78znsualsuwv89j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUGJ0MzgrcXRpT1NFQ2Ju
            SHd4ZjJlMEVzWFZjYlI1NVJOUUR1ZjEyYm5NCk8xR0lqRElQWDBlVmJZaVFjQzVK
            WVJvWHl6MysxQ1ZKc1pIUU43STVvNkUKLS0tIHl3MHlkZUZEbGo0QnFBZVVVYndu
            aHBHTnZGMFp6M0lqc2FDS0JVOUlZaUEKVnePHypLSkdt+l4KDyd2hWjOueSjphDw
            v+EqmH2lJikj0f4roXrhqVamFCOYO7WU1RrDpMiltzW83djf6orIdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T07:42:14Z"
    mac: ENC[AES256_GCM,data:AAtprNJPn512ZX3gv+uwPFEO106kI4cmCInTA8tVjioLTlJ4bGKUvuxyTQqpYQSuXQrP55gZS+FrsKENGInlWJs8Vlq/bToTjx4Paqrfn6dr1tMVP9t4UX9OYgtwSu//qMYyk632X8S2bMB7x8eFitbnhXs82cYM/ssJwuy1Tfs=,iv:urPG7FeCOYAMvrXzSC7LAzMkdUGbSEW5VMvEdx6PdvA=,tag:NRkEubKXwXrGKx/iCvunWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
