apiVersion: v1
kind: Secret
metadata:
    name: podinfo-values
    namespace: podinfo
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:uWqqpNb3LTPHigM0V58tbFJqW8VxRms2cEeZ/NH28+AWRbSdRroRGgUC5faSt+ga7hZ5YDpwwtyLrEgBxg==,iv:qDFLYZ6RKJP0mLQwZewmM+hNWnoEYRg6+Pw40ruolI0=,tag:bax36vabAjYpj/C2zOfIyg==,type:str]
sops:
    age:
        - recipient: age16f57mdcye3txnjuk3kuhquvfvzwl2gqlqzalwh0082z78znsualsuwv89j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUGJ0MzgrcXRpT1NFQ2Ju
            SHd4ZjJlMEVzWFZjYlI1NVJOUUR1ZjEyYm5NCk8xR0lqRElQWDBlVmJZaVFjQzVK
            WVJvWHl6MysxQ1ZKc1pIUU43STVvNkUKLS0tIHl3MHlkZUZEbGo0QnFBZVVVYndu
            aHBHTnZGMFp6M0lqc2FDS0JVOUlZaUEKVnePHypLSkdt+l4KDyd2hWjOueSjphDw
            v+EqmH2lJikj0f4roXrhqVamFCOYO7WU1RrDpMiltzW83djf6orIdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T13:45:10Z"
    mac: ENC[AES256_GCM,data:3kRPimOsCy43O7t1YjKgWuak/tLc9SnOEuac1+c53zCVRu+d5E8dgw1KbgGqab77c71woEAcwcT9R0TomIjt9kpGVzNahtQdDVTEB5cp9blyxREIJ2MX61ffGcsnva5ZiFNkZH0NDGFUxJvp/gbChA5rIhjW6gxdtGkAsBQE5gA=,iv:hyEkMqp5Ea6e2PI8KeiFKC2buqR+rrvLBqFpEo0bw3M=,tag:xje1dkRMzas+Pd+ryQlrxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
