apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  path: ./apps/podinfo
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
